use std::{
    fs,
    io::{Read, Write},
    path::{Path, PathBuf},
    sync::{OnceLock, mpsc},
    thread,
    time::Duration,
};

#[cfg(not(windows))]
use std::time::Instant;

use anyhow::{Context, Result};
use portable_pty::{CommandBuilder, PtySize, native_pty_system};
#[cfg(not(windows))]
use sysinfo::{Pid, ProcessRefreshKind, ProcessesToUpdate, System, UpdateKind};

use crate::session::config::LocalTerminalShell;
use crate::terminal::{BackendCommand, BackendEvent, BackendTx, GuardedBackendEventSender};

#[cfg(not(windows))]
const DIRECTORY_POLL_INTERVAL: Duration = Duration::from_secs(1);

const BASH_INTEGRATION_RC: &str = r#"# Generated by ashell. User startup files remain authoritative.
if [[ ${ASHELL_BASH_LOGIN:-0} == 1 ]]; then
    [[ -r /etc/profile ]] && source /etc/profile
    if [[ -r $HOME/.bash_profile ]]; then
        source "$HOME/.bash_profile"
    elif [[ -r $HOME/.bash_login ]]; then
        source "$HOME/.bash_login"
    elif [[ -r $HOME/.profile ]]; then
        source "$HOME/.profile"
    fi
elif [[ -r $HOME/.bashrc ]]; then
    source "$HOME/.bashrc"
fi

if [[ -z ${__ASHELL_BASH_INTEGRATION_ACTIVE:-} ]]; then
    __ASHELL_BASH_INTEGRATION_ACTIVE=1
    __ashell_prompt_suffix='\[\e]133;B\a\]'
    __ashell_secondary_prefix='\[\e]133;A;k=s\a\]'

    __ashell_install_prompt_markers() {
        PS1=${PS1//"$__ashell_prompt_suffix"/}
        PS1+=$__ashell_prompt_suffix
        PS2=${PS2//"$__ashell_secondary_prefix"/}
        PS2=${PS2//"$__ashell_prompt_suffix"/}
        PS2="${__ashell_secondary_prefix}${PS2}${__ashell_prompt_suffix}"
    }

    __ashell_precmd() {
        local __ashell_last_status=$?
        local __ashell_cwd=$PWD
        __ashell_install_prompt_markers
        if [[ ${ASHELL_WINDOWS_GIT_BASH:-0} == 1 ]]; then
            __ashell_cwd=$(pwd -W 2>/dev/null) || __ashell_cwd=$PWD
        fi
        printf '\033]133;D;%s\007\033]0;ASHELL_CWD:%s\007\033]133;A\007' \
            "$__ashell_last_status" "$__ashell_cwd"
        return "$__ashell_last_status"
    }

    case $(declare -p PROMPT_COMMAND 2>/dev/null) in
        'declare -a'*)
            PROMPT_COMMAND+=(__ashell_precmd)
            ;;
        *)
            [[ -n ${PROMPT_COMMAND:-} ]] && PROMPT_COMMAND+=$'\n'
            PROMPT_COMMAND+='__ashell_precmd'
            ;;
    esac
    __ashell_install_prompt_markers
fi
"#;

const ZSH_ENV_WRAPPER: &str = r#"# Generated by ashell. Redirect startup back to the user's files first.
typeset -g ASHELL_USER_ZDOTDIR="${ASHELL_ORIGINAL_ZDOTDIR:-$HOME}"
if [[ "$ASHELL_USER_ZDOTDIR" != "$ASHELL_INTEGRATION_ZDOTDIR" && -r "$ASHELL_USER_ZDOTDIR/.zshenv" ]]; then
    export ZDOTDIR="$ASHELL_USER_ZDOTDIR"
    source "$ASHELL_USER_ZDOTDIR/.zshenv"
    typeset -g ASHELL_USER_ZDOTDIR="${ZDOTDIR:-$ASHELL_USER_ZDOTDIR}"
fi
export ASHELL_USER_ZDOTDIR
export ZDOTDIR="$ASHELL_INTEGRATION_ZDOTDIR"
"#;

const ZSH_INTEGRATION_RC: &str = r#"# Generated by ashell. User startup files remain authoritative.
if [[ "$ASHELL_USER_ZDOTDIR" != "$ASHELL_INTEGRATION_ZDOTDIR" && -r "$ASHELL_USER_ZDOTDIR/.zshrc" ]]; then
    export ZDOTDIR="$ASHELL_USER_ZDOTDIR"
    source "$ASHELL_USER_ZDOTDIR/.zshrc"
    typeset -g ASHELL_USER_ZDOTDIR="${ZDOTDIR:-$ASHELL_USER_ZDOTDIR}"
    export ZDOTDIR="$ASHELL_INTEGRATION_ZDOTDIR"
fi

if [[ -z ${__ASHELL_ZSH_INTEGRATION_ACTIVE:-} ]]; then
    typeset -g __ASHELL_ZSH_INTEGRATION_ACTIVE=1
    typeset -g __ashell_prompt_suffix=$'%{\e]133;B\a%}'
    typeset -g __ashell_secondary_prefix=$'%{\e]133;A;k=s\a%}'

    __ashell_install_prompt_markers() {
        PROMPT=${PROMPT//$__ashell_prompt_suffix/}
        PROMPT+=$__ashell_prompt_suffix
        PS2=${PS2//$__ashell_secondary_prefix/}
        PS2=${PS2//$__ashell_prompt_suffix/}
        PS2="${__ashell_secondary_prefix}${PS2}${__ashell_prompt_suffix}"
    }

    __ashell_precmd() {
        local __ashell_last_status=$?
        __ashell_install_prompt_markers
        print -rn -- $'\e]133;D;'"$__ashell_last_status"$'\a'
        print -rn -- $'\e]0;ASHELL_CWD:'"$PWD"$'\a'
        print -rn -- $'\e]133;A\a'
        return "$__ashell_last_status"
    }

    __ashell_preexec() {
        print -rn -- $'\e]133;C\a'
    }

    autoload -Uz add-zsh-hook
    add-zsh-hook -d precmd __ashell_precmd 2>/dev/null
    add-zsh-hook -d preexec __ashell_preexec 2>/dev/null
    add-zsh-hook precmd __ashell_precmd
    add-zsh-hook preexec __ashell_preexec
    __ashell_install_prompt_markers
fi
export ZDOTDIR="$ASHELL_USER_ZDOTDIR"
"#;

const FISH_INTEGRATION_COMMAND: &str = r#"
if status --is-interactive; and not functions -q __ashell_original_fish_prompt
    functions -c fish_prompt __ashell_original_fish_prompt

    function __ashell_common_prompt
        set -l __ashell_last_status $status
        printf '\033]133;D;%s\007' $__ashell_last_status
        printf '\033]0;ASHELL_CWD:%s\007' $PWD
        printf '\033]133;A\007'
        return $__ashell_last_status
    end

    function __ashell_preexec --on-event fish_preexec
        printf '\033]133;C\007'
    end

    function fish_prompt
        __ashell_common_prompt
        __ashell_original_fish_prompt
        printf '\033]133;B\007'
    end
end
"#;

#[cfg(any(windows, test))]
const POWERSHELL_SHELL_INTEGRATION: &str = r#"& {
    $global:AshellOriginalPrompt = $function:prompt
    function global:prompt {
        $promptText = if ($global:AshellOriginalPrompt) { & $global:AshellOriginalPrompt } else { "PS $PWD> " }
        $cwd = $PWD.ProviderPath
        $encoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($cwd))
        [Console]::Write("$([char]27)]133;D$([char]7)$([char]27)]133;A$([char]7)")
        [Console]::Write("$([char]27)]0;ASHELL_CWD_B64:$encoded$([char]7)")
        "$promptText$([char]27)]133;B$([char]7)"
    }

    try {
        $options = Get-PSReadLineOption -ErrorAction Stop
        $continuation = "$([char]27)]133;A;k=s$([char]7)$($options.ContinuationPrompt)$([char]27)]133;B$([char]7)"
        Set-PSReadLineOption -ContinuationPrompt $continuation -ErrorAction Stop
    } catch {}
}"#;

#[derive(Debug)]
struct ShellIntegrationPaths {
    bash_rc: PathBuf,
    zsh_dir: PathBuf,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FileShellIntegration {
    Bash { login: bool },
    Zsh,
    Fish,
}

static SHELL_INTEGRATION_PATHS: OnceLock<Result<ShellIntegrationPaths, String>> = OnceLock::new();

fn file_shell_integration(executable: &Path, login_bash: bool) -> Option<FileShellIntegration> {
    let executable_name = executable
        .file_stem()?
        .to_string_lossy()
        .to_ascii_lowercase();
    match executable_name.as_str() {
        "bash" => Some(FileShellIntegration::Bash { login: login_bash }),
        "zsh" => Some(FileShellIntegration::Zsh),
        "fish" => Some(FileShellIntegration::Fish),
        _ => None,
    }
}

fn shell_integration_paths() -> Result<&'static ShellIntegrationPaths> {
    SHELL_INTEGRATION_PATHS
        .get_or_init(|| create_shell_integration_paths().map_err(|error| format!("{error:#}")))
        .as_ref()
        .map_err(|message| anyhow::anyhow!("{message}"))
}

fn create_shell_integration_paths() -> Result<ShellIntegrationPaths> {
    let root = std::env::temp_dir().join(format!(
        "ashell-shell-integration-{}-{}",
        std::process::id(),
        uuid::Uuid::new_v4()
    ));
    let zsh_dir = root.join("zsh");

    #[cfg(unix)]
    {
        use std::os::unix::fs::DirBuilderExt;

        fs::DirBuilder::new()
            .recursive(true)
            .mode(0o700)
            .create(&zsh_dir)
            .with_context(|| format!("create shell integration directory {}", zsh_dir.display()))?;
    }
    #[cfg(not(unix))]
    fs::create_dir_all(&zsh_dir)
        .with_context(|| format!("create shell integration directory {}", zsh_dir.display()))?;

    let bash_rc = root.join("bashrc");
    write_shell_integration_file(&bash_rc, BASH_INTEGRATION_RC)?;
    write_shell_integration_file(&zsh_dir.join(".zshenv"), ZSH_ENV_WRAPPER)?;
    write_shell_integration_file(&zsh_dir.join(".zshrc"), ZSH_INTEGRATION_RC)?;

    Ok(ShellIntegrationPaths { bash_rc, zsh_dir })
}

fn write_shell_integration_file(path: &Path, contents: &str) -> Result<()> {
    let mut options = fs::OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;

        options.mode(0o600);
    }

    let mut file = options
        .open(path)
        .with_context(|| format!("create shell integration file {}", path.display()))?;
    file.write_all(contents.as_bytes())
        .with_context(|| format!("write shell integration file {}", path.display()))
}

fn configure_file_shell_integration(
    cmd: &mut CommandBuilder,
    executable: &Path,
    login_bash: bool,
) -> Result<bool> {
    let Some(integration) = file_shell_integration(executable, login_bash) else {
        return Ok(false);
    };

    match integration {
        FileShellIntegration::Bash { login } => {
            let paths = shell_integration_paths()?;
            cmd.env("ASHELL_BASH_LOGIN", if login { "1" } else { "0" });
            cmd.env("ASHELL_WINDOWS_GIT_BASH", if login { "1" } else { "0" });
            cmd.arg("--rcfile");
            cmd.arg(paths.bash_rc.as_os_str());
            cmd.arg("-i");
        }
        FileShellIntegration::Zsh => {
            let paths = shell_integration_paths()?;
            if let Some(original_zdotdir) = std::env::var_os("ZDOTDIR") {
                cmd.env("ASHELL_ORIGINAL_ZDOTDIR", original_zdotdir);
            }
            cmd.env("ASHELL_INTEGRATION_ZDOTDIR", paths.zsh_dir.as_os_str());
            cmd.env("ZDOTDIR", paths.zsh_dir.as_os_str());
        }
        FileShellIntegration::Fish => {
            cmd.args(["-C", FISH_INTEGRATION_COMMAND]);
        }
    }
    cmd.env("ASHELL_SHELL_INTEGRATION", "1");
    Ok(true)
}

#[cfg(any(windows, test))]
fn command_prompt_with_shell_integration(original_prompt: &str) -> String {
    format!("\x1b]133;D\x07\x1b]133;A\x07\x1b]0;ASHELL_CWD:$P\x07{original_prompt}\x1b]133;B\x07")
}

#[cfg(not(windows))]
fn local_process_directory(system: &mut System, pid: Pid) -> Option<std::path::PathBuf> {
    system.refresh_processes_specifics(
        ProcessesToUpdate::Some(&[pid]),
        false,
        ProcessRefreshKind::nothing().with_cwd(UpdateKind::Always),
    );
    system
        .process(pid)
        .and_then(|process| process.cwd())
        .map(std::path::PathBuf::from)
}

#[derive(Debug, Clone)]
pub struct LocalTerminalShellLaunch {
    pub executable: PathBuf,
}

/// Resolves a configured local shell to an executable available on this host.
pub fn resolve_local_terminal_shell(
    shell: LocalTerminalShell,
) -> anyhow::Result<LocalTerminalShellLaunch> {
    #[cfg(not(windows))]
    let _ = shell;

    #[cfg(windows)]
    {
        let executable = match shell {
            LocalTerminalShell::WindowsPowerShell => resolve_windows_powershell(),
            LocalTerminalShell::PowerShell7 => resolve_powershell7(),
            LocalTerminalShell::CommandPrompt => resolve_command_prompt(),
            LocalTerminalShell::GitBash => resolve_git_bash(),
        }
        .ok_or_else(|| anyhow::anyhow!("configured local shell is not installed: {shell:?}"))?;
        return Ok(LocalTerminalShellLaunch { executable });
    }

    #[cfg(not(windows))]
    {
        let executable = std::env::var_os("SHELL")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("/bin/zsh"));
        Ok(LocalTerminalShellLaunch { executable })
    }
}

pub fn local_terminal_shell_available(shell: LocalTerminalShell) -> bool {
    resolve_local_terminal_shell(shell).is_ok()
}

#[cfg(windows)]
fn existing_file(path: PathBuf) -> Option<PathBuf> {
    path.is_file().then_some(path)
}

#[cfg(windows)]
fn env_path(name: &str) -> Option<PathBuf> {
    std::env::var_os(name).map(PathBuf::from)
}

#[cfg(windows)]
fn find_on_path(name: &str, predicate: impl Fn(&Path) -> bool) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .map(|directory| directory.join(name))
        .find(|candidate| candidate.is_file() && predicate(candidate))
}

#[cfg(windows)]
fn resolve_windows_powershell() -> Option<PathBuf> {
    let system_root = env_path("SystemRoot").unwrap_or_else(|| PathBuf::from(r"C:\Windows"));
    existing_file(system_root.join(r"System32\WindowsPowerShell\v1.0\powershell.exe"))
        .or_else(|| find_on_path("powershell.exe", |_| true))
}

#[cfg(windows)]
fn resolve_powershell7() -> Option<PathBuf> {
    let mut roots = Vec::new();
    if let Some(program_files) = env_path("ProgramFiles") {
        roots.push(program_files.join("PowerShell"));
    }
    if let Some(program_files) = env_path("ProgramW6432") {
        roots.push(program_files.join("PowerShell"));
    }
    if let Some(program_files) = env_path("ProgramFiles(x86)") {
        roots.push(program_files.join("PowerShell"));
    }
    if let Some(local_app_data) = env_path("LOCALAPPDATA") {
        roots.push(local_app_data.join(r"Programs\PowerShell"));
    }

    let mut candidates = Vec::new();
    if let Some(local_app_data) = env_path("LOCALAPPDATA") {
        candidates.push(local_app_data.join(r"Microsoft\WindowsApps\pwsh.exe"));
    }
    if let Some(scoop) = env_path("SCOOP") {
        candidates.push(scoop.join(r"apps\powershell\current\pwsh.exe"));
    }
    if let Some(user_profile) = env_path("USERPROFILE") {
        candidates.push(user_profile.join(r"scoop\apps\powershell\current\pwsh.exe"));
    }
    for root in roots {
        if let Some(candidate) = existing_file(root.join("pwsh.exe")) {
            candidates.push(candidate);
        }
        let Ok(entries) = std::fs::read_dir(root) else {
            continue;
        };
        let mut versions = entries
            .filter_map(|entry| entry.ok())
            .filter(|entry| entry.file_type().map(|kind| kind.is_dir()).unwrap_or(false))
            .filter(|entry| {
                entry
                    .file_name()
                    .to_string_lossy()
                    .chars()
                    .all(|character| character.is_ascii_digit() || character == '.')
            })
            .collect::<Vec<_>>();
        versions.sort_by_key(|entry| entry.file_name());
        candidates.extend(
            versions
                .into_iter()
                .rev()
                .filter_map(|entry| existing_file(entry.path().join("pwsh.exe"))),
        );
    }

    candidates
        .into_iter()
        .next()
        .or_else(|| find_on_path("pwsh.exe", |_| true))
}

#[cfg(windows)]
fn resolve_command_prompt() -> Option<PathBuf> {
    env_path("ComSpec")
        .and_then(existing_file)
        .or_else(|| {
            let system_root =
                env_path("SystemRoot").unwrap_or_else(|| PathBuf::from(r"C:\Windows"));
            existing_file(system_root.join(r"System32\cmd.exe"))
        })
        .or_else(|| find_on_path("cmd.exe", |_| true))
}

#[cfg(windows)]
fn resolve_git_bash() -> Option<PathBuf> {
    let mut candidates = Vec::new();
    for variable in ["ProgramFiles", "ProgramW6432", "ProgramFiles(x86)"] {
        if let Some(program_files) = env_path(variable) {
            candidates.push(program_files.join(r"Git\bin\bash.exe"));
        }
    }
    if let Some(local_app_data) = env_path("LOCALAPPDATA") {
        candidates.push(local_app_data.join(r"Programs\Git\bin\bash.exe"));
    }
    if let Some(scoop) = env_path("SCOOP") {
        candidates.push(scoop.join(r"apps\git\current\bin\bash.exe"));
    }
    if let Some(user_profile) = env_path("USERPROFILE") {
        candidates.push(user_profile.join(r"scoop\apps\git\current\bin\bash.exe"));
    }

    candidates.into_iter().find_map(existing_file).or_else(|| {
        find_on_path("bash.exe", |candidate| {
            let path = candidate.to_string_lossy().to_ascii_lowercase();
            path.contains("\\git\\") || path.contains("/git/")
        })
    })
}

pub fn spawn_local_terminal_at(
    tab_id: String,
    cols: u16,
    rows: u16,
    events: GuardedBackendEventSender,
    initial_directory: Option<&Path>,
    shell: LocalTerminalShell,
) -> Result<BackendTx> {
    let pty_system = native_pty_system();
    let pair = pty_system
        .openpty(PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })
        .context("open local PTY")?;

    let launch = resolve_local_terminal_shell(shell).context("resolve local shell")?;
    let mut cmd = CommandBuilder::new(&launch.executable);
    #[cfg(windows)]
    {
        match shell {
            LocalTerminalShell::WindowsPowerShell | LocalTerminalShell::PowerShell7 => {
                cmd.args([
                    "-NoLogo",
                    "-NoExit",
                    "-Command",
                    POWERSHELL_SHELL_INTEGRATION,
                ]);
            }
            LocalTerminalShell::CommandPrompt => {
                let original_prompt =
                    std::env::var("PROMPT").unwrap_or_else(|_| "$P$G".to_string());
                cmd.args(["/Q"]);
                cmd.env(
                    "PROMPT",
                    command_prompt_with_shell_integration(&original_prompt),
                );
            }
            LocalTerminalShell::GitBash => {
                cmd.env("CHERE_INVOKING", "1");
            }
        }
    }
    let login_bash = cfg!(windows) && shell == LocalTerminalShell::GitBash;
    let shell_integration_configured =
        match configure_file_shell_integration(&mut cmd, &launch.executable, login_bash) {
            Ok(configured) => configured,
            Err(error) => {
                tracing::warn!(
                    "[local] shell integration unavailable for {}: {error:#}",
                    launch.executable.display()
                );
                false
            }
        };
    #[cfg(windows)]
    if shell == LocalTerminalShell::GitBash && !shell_integration_configured {
        cmd.args(["--login", "-i"]);
    }
    #[cfg(not(windows))]
    let _ = shell_integration_configured;
    cmd.env(
        "TERM",
        std::env::var("TERM").unwrap_or_else(|_| "xterm-256color".into()),
    );
    cmd.env(
        "COLORTERM",
        std::env::var("COLORTERM").unwrap_or_else(|_| "truecolor".into()),
    );
    cmd.env("TERM_PROGRAM", "ashell");
    if let Ok(path) = std::env::var("PATH") {
        cmd.env("PATH", path);
    }
    if let Ok(lang) = std::env::var("LANG") {
        cmd.env("LANG", lang);
    } else {
        cmd.env("LANG", "en_US.UTF-8");
    }
    if let Ok(home) = std::env::var("HOME") {
        cmd.env("HOME", home);
    }
    if let Some(directory) = initial_directory.filter(|path| path.is_dir()) {
        cmd.cwd(directory.as_os_str());
    }
    cmd.env("SHELL", launch.executable.as_os_str());
    let mut child = pair.slave.spawn_command(cmd).context("spawn local shell")?;
    #[cfg(not(windows))]
    let child_pid = child.process_id().map(Pid::from_u32);
    drop(pair.slave);

    let master = pair.master;
    let mut reader = master.try_clone_reader().context("clone PTY reader")?;
    let mut writer = master.take_writer().context("take PTY writer")?;
    let (cmd_tx, cmd_rx) = mpsc::channel::<BackendCommand>();

    let read_tab = tab_id.clone();
    let read_events = events.clone();
    thread::spawn(move || {
        let mut buf = [0u8; 8192];
        loop {
            match reader.read(&mut buf) {
                Ok(0) => break,
                Ok(n) => {
                    let _ = read_events.send(BackendEvent::Output {
                        tab_id: read_tab.clone(),
                        bytes: buf[..n].to_vec(),
                    });
                }
                Err(err) => {
                    let _ = read_events.send(BackendEvent::Closed {
                        tab_id: read_tab.clone(),
                        reason: format!("local read error: {err}"),
                    });
                    return;
                }
            }
        }
        let _ = read_events.send(BackendEvent::Closed {
            tab_id: read_tab,
            reason: "local shell closed".into(),
        });
    });

    let write_tab = tab_id.clone();
    let write_events = events.clone();
    thread::spawn(move || {
        #[cfg(not(windows))]
        let mut process_system = System::new();
        #[cfg(not(windows))]
        let mut last_directory = None;
        #[cfg(not(windows))]
        let mut last_directory_check = None;

        loop {
            match cmd_rx.recv_timeout(Duration::from_millis(100)) {
                Ok(command) => match command {
                    BackendCommand::Input(bytes) => {
                        if let Err(err) = writer.write_all(&bytes) {
                            let _ = write_events.send(BackendEvent::Closed {
                                tab_id: write_tab.clone(),
                                reason: format!("local write error: {err}"),
                            });
                            break;
                        }
                        let _ = writer.flush();
                    }
                    BackendCommand::Resize { cols, rows } => {
                        let _ = master.resize(PtySize {
                            rows,
                            cols,
                            pixel_width: 0,
                            pixel_height: 0,
                        });
                    }
                    BackendCommand::Close => break,
                    BackendCommand::SampleMetrics
                    | BackendCommand::SampleProcesses
                    | BackendCommand::SamplePorts
                    | BackendCommand::TerminateProcess { .. } => {}
                },
                Err(mpsc::RecvTimeoutError::Timeout) => {
                    if let Ok(Some(status)) = child.try_wait() {
                        let _ = write_events.send(BackendEvent::Closed {
                            tab_id: write_tab,
                            reason: format!("local shell exited: {status}"),
                        });
                        return;
                    }
                }
                Err(mpsc::RecvTimeoutError::Disconnected) => break,
            }

            #[cfg(not(windows))]
            {
                if last_directory_check.is_none_or(|checked_at: Instant| {
                    checked_at.elapsed() >= DIRECTORY_POLL_INTERVAL
                }) {
                    last_directory_check = Some(Instant::now());
                    if let Some(directory) =
                        child_pid.and_then(|pid| local_process_directory(&mut process_system, pid))
                    {
                        if last_directory.as_ref() != Some(&directory) {
                            last_directory = Some(directory.clone());
                            let _ = write_events.send(BackendEvent::LocalDirectoryChanged {
                                tab_id: write_tab.clone(),
                                path: directory,
                            });
                        }
                    }
                }
            }
        }
        let _ = child.kill();
    });

    let _ = events.send(BackendEvent::Status {
        tab_id,
        text: "local shell ready".into(),
    });

    Ok(BackendTx::Local(cmd_tx))
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::{
        BASH_INTEGRATION_RC, FISH_INTEGRATION_COMMAND, FileShellIntegration,
        POWERSHELL_SHELL_INTEGRATION, ZSH_ENV_WRAPPER, ZSH_INTEGRATION_RC,
        command_prompt_with_shell_integration, file_shell_integration,
    };

    #[test]
    fn recognizes_supported_file_based_shells_on_unix_and_windows() {
        assert_eq!(
            file_shell_integration(Path::new("/bin/bash"), false),
            Some(FileShellIntegration::Bash { login: false })
        );
        assert_eq!(
            file_shell_integration(Path::new("bash.exe"), true),
            Some(FileShellIntegration::Bash { login: true })
        );
        assert_eq!(
            file_shell_integration(Path::new("/bin/zsh"), false),
            Some(FileShellIntegration::Zsh)
        );
        assert_eq!(
            file_shell_integration(Path::new("/opt/homebrew/bin/fish"), false),
            Some(FileShellIntegration::Fish)
        );
        assert_eq!(file_shell_integration(Path::new("pwsh.exe"), false), None);
    }

    #[test]
    fn shell_integrations_mark_prompt_and_command_boundaries() {
        for integration in [
            BASH_INTEGRATION_RC,
            ZSH_INTEGRATION_RC,
            FISH_INTEGRATION_COMMAND,
            POWERSHELL_SHELL_INTEGRATION,
        ] {
            assert!(integration.contains("133;A"));
            assert!(integration.contains("133;B"));
            assert!(integration.contains("133;C") || integration.contains("133;D"));
        }
        assert!(BASH_INTEGRATION_RC.contains("133;A;k=s"));
        assert!(ZSH_INTEGRATION_RC.contains("133;A;k=s"));
        assert!(POWERSHELL_SHELL_INTEGRATION.contains("133;A;k=s"));

        let cmd_prompt = command_prompt_with_shell_integration("$P$G");
        assert!(cmd_prompt.contains("133;A"));
        assert!(cmd_prompt.contains("133;B"));
        assert!(cmd_prompt.contains("ASHELL_CWD:$P"));
    }

    #[test]
    fn startup_wrappers_load_user_configuration_before_installing_hooks() {
        assert!(BASH_INTEGRATION_RC.contains("$HOME/.bashrc"));
        assert!(BASH_INTEGRATION_RC.contains("$HOME/.bash_profile"));
        assert!(ZSH_ENV_WRAPPER.contains("$ASHELL_USER_ZDOTDIR/.zshenv"));
        assert!(ZSH_INTEGRATION_RC.contains("$ASHELL_USER_ZDOTDIR/.zshrc"));
    }
}
